Repository Apptive-Game-Team/Cross-The-Line, pull requests merged in 2025-05, with the labels that each got.

#12 [Chore] .editconfig 수정
  .editorconfig
  dontcrosstheline/Directory.Build.props
Labels: chore

#15 docs: Update README.md
  README.md
Labels: documentation

#18 docs: Create auto_assign.yml
  .github/auto_assign.yml
Labels: documentation

#23 조건에 따라 의뢰를 필터링하고 랜덤 의뢰를 주는 기능
  CrossTheLine/Assets/Plugins/TextMesh Pro/Fonts/Galmuri11.ttf.meta
  CrossTheLine/Assets/Plugins/TextMesh Pro/Resources/Fonts & Materials/Galmuri11 SDF.asset.meta
  CrossTheLine/Assets/Plugins/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
  CrossTheLine/Assets/Plugins/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF.asset
  CrossTheLine/Assets/Plugins/TextMesh Pro/Resources/TMP Settings.asset
  CrossTheLine/Assets/Resources/Assets/Data/ContentTable.csv
  CrossTheLine/Assets/Scenes/Request.unity
  CrossTheLine/Assets/ScriptableObjects/Events/Gameplay.meta
  CrossTheLine/Assets/ScriptableObjects/Events/Gameplay/OnDayChanged.asset
  CrossTheLine/Assets/ScriptableObjects/Events/Gameplay/OnDayChanged.asset.meta
  CrossTheLine/Assets/ScriptableObjects/Events/Request/OnAcceptRequest.asset
  CrossTheLine/Assets/ScriptableObjects/Events/Request/OnAcceptRequest.asset.meta
  CrossTheLine/Assets/ScriptableObjects/Events/Request/OnDayChanged.asset
  CrossTheLine/Assets/ScriptableObjects/Events/Request/OnDayChanged.asset.meta
  CrossTheLine/Assets/ScriptableObjects/Events/Request/OnRejectRequest.asset
  CrossTheLine/Assets/ScriptableObjects/Events/Request/OnRejectRequest.asset.meta
  CrossTheLine/Assets/ScriptableObjects/Gameplay.meta
  CrossTheLine/Assets/ScriptableObjects/Gameplay/PlayerStatus.asset
  CrossTheLine/Assets/ScriptableObjects/Gameplay/PlayerStatus.asset.meta
  CrossTheLine/Assets/ScriptableObjects/Request/RequestSO.asset
  CrossTheLine/Assets/ScriptableObjects/Settings.meta
  CrossTheLine/Assets/ScriptableObjects/Settings/TMPFontChanger.asset
  CrossTheLine/Assets/ScriptableObjects/Settings/TMPFontChanger.asset.meta
  CrossTheLine/Assets/Scripts/Events/ScriptableObjects/IntEventChannelSO.cs
  CrossTheLine/Assets/Scripts/Events/ScriptableObjects/IntEventChannelSO.cs.meta
  CrossTheLine/Assets/Scripts/Events/ScriptableObjects/VoidEventChannelSO.cs
  CrossTheLine/Assets/Scripts/Excel/ExcelImporter.cs
  CrossTheLine/Assets/Scripts/Excel/ScriptableObjects/ContentDataSO.cs
  CrossTheLine/Assets/Scripts/Excel/ScriptableObjects/ContentDatabaseSO.cs
  CrossTheLine/Assets/Scripts/Gameplay.meta
  CrossTheLine/Assets/Scripts/Gameplay/StatusSO.cs
  CrossTheLine/Assets/Scripts/Gameplay/StatusSO.cs.meta
  CrossTheLine/Assets/Scripts/Settings.meta
  CrossTheLine/Assets/Scripts/Settings/Fonts.meta
  CrossTheLine/Assets/Scripts/Settings/Fonts/TMPFontChanger.cs
  CrossTheLine/Assets/Scripts/Settings/Fonts/TMPFontChanger.cs.meta
  CrossTheLine/Assets/Scripts/UI/DayManager.cs
  CrossTheLine/Assets/Scripts/UI/RequestManager.cs
  CrossTheLine/Assets/Scripts/UI/ScriptableObjects/RequestSO.cs
Labels: feature
